INSERT INTO profiles (user_id, bio, interests, min_age_preference, max_age_preference, preferred_city, altura, lifestyle, preferences, profile_picture) VALUES
(1, 'A passionate traveler and foodie.', '["travel", "food", "music"]', 25, 35, 'Madrid', 175, '["active", "adventurous"]', '["cooking", "photography"]', null),
(2, 'Lover of art and culture.', '["art", "culture", "reading"]', 20, 30, 'Barcelona', 160, '["creative", "thoughtful"]', '["writing", "painting"]', null),
(3, 'Tech enthusiast and gamer.', '["technology", "gaming"]', 18, 28, 'Barcelona', 180, '["introverted", "analytical"]', '["programming", "gaming"]', null),
(4, 'Fitness junkie and health advocate.', '["fitness", "health"]', 22, 32, 'Barcelona', 165, '["motivated", "disciplined"]', '["yoga", "nutrition"]', null),
(5, 'Nature lover and environmentalist.', '["nature", "sustainability"]', 20, 30, 'Madrid', 170, '["outdoorsy", "passionate"]', '["hiking", "gardening"]', null),
(6, 'Music lover and aspiring musician.', '["music", "performance"]', 18, 28, 'Barcelona', 172, '["creative", "expressive"]', '["singing", "playing instruments"]', null),
(7, 'Food blogger and culinary explorer.', '["food", "blogging"]', 21, 31, 'Madrid', 168, '["curious", "adventurous"]', '["cooking", "tasting"]', null),
(8, 'Bookworm and literature enthusiast.', '["reading", "writing"]', 19, 29, 'Barcelona', 162, '["thoughtful", "imaginative"]', '["novels", "poetry"]', null),
(9, 'Sports fan and active lifestyle advocate.', '["sports", "fitness"]', 20, 30, 'Barcelona', 178, '["energetic", "competitive"]', '["football", "running"]', null),
(10, 'Fashion enthusiast and style blogger.', '["fashion", "style"]', 22, 32, 'Madrid', 165, '["creative", "trendy"]', '["design", "shopping"]', null),
(11, 'Tech entrepreneur and innovator.', '["entrepreneurship", "technology"]', 25, 35, 'Madrid', 180, '["ambitious", "visionary"]', '["startups", "innovation"]', null),
(12, 'Animal lover and volunteer.', '["animals", "volunteering"]', 20, 30, 'Barcelona', 170, '["compassionate", "caring"]', '["animal rescue", "community service"]', null),
(13, 'History buff and travel enthusiast.', '["history", "travel"]', 22, 32, 'Madrid', 175, '["curious", "adventurous"]', '["exploring", "learning"]', null),
(14, 'Creative writer and storyteller.', '["writing", "storytelling"]', 18, 28, 'Barcelona', 160, '["imaginative", "thoughtful"]', '["fiction", "screenwriting"]', null),
(15, 'Fitness coach and wellness advocate.', '["fitness", "wellness"]', 25, 35, 'Madrid', 177, '["motivated", "supportive"]', '["personal training", "nutrition"]', null),
(16, 'Artistic soul and painter.', '["art", "painting"]', 20, 30, 'Barcelona', 165, '["creative", "expressive"]', '["watercolor", "acrylic"]', null),
(17, 'Gamer and tech enthusiast.', '["gaming", "technology"]', 18, 28, 'Madrid', 180, '["analytical", "strategic"]', '["esports", "streaming"]', null),
(18, 'Culinary artist and chef.', '["cooking", "culinary arts"]', 22, 32, 'Barcelona', 170, '["creative", "passionate"]', '["baking", "cooking classes"]', null),
(19, 'Outdoor adventurer and hiker.', '["hiking", "outdoors"]', 20, 30, 'Madrid', 175, '["adventurous", "active"]', '["camping", "exploring"]', null),
(20, 'Social media influencer and content creator.', '["social media", "content creation"]', 21, 31, 'Barcelona', 168, '["creative", "outgoing"]', '["vlogging", "photography"]', null),
(21, 'Tech enthusiast and software developer.', '["technology", "programming"]', 22, 32, 'Madrid', 180, '["analytical", "problem-solver"]', '["coding", "app development"]', null),
(22, 'Fashion designer and stylist.', '["fashion", "design"]', 20, 30, 'Barcelona', 165, '["creative", "innovative"]', '["designing", "sewing"]', null),
(23, 'Fitness enthusiast and personal trainer.', '["fitness", "health"]', 25, 35, 'Madrid', 177, '["motivated", "supportive"]', '["gym", "nutrition"]', null),
(24, 'Travel blogger and explorer.', '["travel", "blogging"]', 21, 31, 'Barcelona', 170, '["curious", "adventurous"]', '["photography", "writing"]', null),
(25, 'Music producer and DJ.', '["music", "production"]', 22, 32, 'Madrid', 180, '["creative", "passionate"]', '["mixing", "performing"]', null),
(26, 'Environmental activist and sustainability advocate.', '["environment", "sustainability"]', 20, 30, 'Barcelona', 165, '["passionate", "dedicated"]', '["recycling", "community service"]', null),
(27, 'Digital marketer and entrepreneur.', '["marketing", "entrepreneurship"]', 25, 35, 'Madrid', 175, '["ambitious", "strategic"]', '["SEO", "content marketing"]', null),
(28, 'Creative director and visual artist.', '["art", "design"]', 22, 32, 'Barcelona', 170, '["innovative", "creative"]', '["graphic design", "illustration"]', null),
(29, 'Sports coach and mentor.', '["sports", "coaching"]', 20, 30, 'Madrid', 180, '["motivated", "supportive"]', '["team building", "training"]', null),
(30, 'Writer and poet.', '["writing", "poetry"]', 21, 31, 'Barcelona', 165, '["thoughtful", "imaginative"]', '["fiction", "poetry"]', null),
(31, 'Tech consultant and advisor.', '["technology", "consulting"]', 25, 35, 'Madrid', 180, '["analytical", "strategic"]', '["IT solutions", "business strategy"]', null),
(32, 'Fashion influencer and stylist.', '["fashion", "influencing"]', 20, 30, 'Barcelona', 165, '["creative", "trendy"]', '["styling", "blogging"]', null),
(33, 'Health coach and wellness advocate.', '["health", "wellness"]', 22, 32, 'Madrid', 175, '["motivated", "supportive"]', '["nutrition", "fitness"]', null);